# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836ef090f9778ddb7b307bf30dd23ec815b791fbfa33edc137f43f887a5258d7791eede6f1ba3b7b3fa50f75e37d9ff1bec284e1c7bc574749b10716cd0eb7d2

test:
  secret_key_base: b995ef4ba9fd6fd926ac75a1f196f7423f0e2834758015e95dae4e5554530a035fa14f5be73f118c8210c270b988916ceb18a1544c113a03f4bfecbcbb760952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
